site_name: Cuadratura Gaussiana

theme:
  name: material

nav:
  - Inicio: index.md
  - Explicación: explicacion.md
  - Código fuente: tutorials.md
  - Referencia: referencia.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
